baseURL = 'https://zoriya.dev/'
languageCode = 'en'
enableRobotsTXT = true
googleAnalytics = "G-KK12E7TNEC"
enableEmoji = true
titleCaseStyle = 'none'

[pagination]
pagerSize = 50

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"
